Repository AOSSIE-Org/PictoPy, pull requests merged in 2025-07, with the labels that each got.

#449 Rename workflows and setup Github secrets to generate builds
  .github/workflows/build-and-release.yml
  .github/workflows/docs-deploy.yml
  .github/workflows/pr-check-build.yml
  .github/workflows/pr-check-tests.yml
  CONTRIBUTING.md
  README.md
  docs/Manual_Setup_Guide.md
  docs/Script_Setup_Guide.md
  docs/backend/docker-setup.md
  docs/frontend/docker-setup.md
  frontend/src-tauri/tauri.conf.json
Labels: GSoC 2025

#457 Add Release Drafter configuration and workflow
  .github/release-drafter-config.yml
  .github/workflows/build-and-release.yml
  .github/workflows/update-release-drafter.yml
Labels: enhancement, CI/CD

#460 Fix: release-drafter workflow error
  .github/workflows/update-release-drafter.yml
Labels: bug, CI/CD

#462 Revise docs for setup links and feature details
  docs/index.md
  docs/overview/features.md
  docs/setup.md
Labels: documentation, good first issue
